#!/usr/bin/env python

# import of relevant libraries
import rospy # module for ROS APIs
from geometry_msgs.msg import Polygon, Point32

DEFAULT_WP_TOPIC = "waypoints"
RATE = 10

def waypoint_generator(x1, y1, x2, y2, x3, y3):
    wp_msg = Polygon()
    wp_msg.points = [
        Point32(x=x1, y=y1),
        Point32(x=x2, y=y2),
        Point32(x=x3, y=y3)
    ]
    return wp_msg


def main():
    """ Main function """
    """ waypoint generator by user input and publish through ROS message of type "Polygon" """

    # initialization of node
    rospy.init_node("waypoint_send")

    # Sleep for a few seconds to wait for the registration.
    rospy.sleep(2)

    waypoint_publisher = rospy.Publisher(DEFAULT_WP_TOPIC, Polygon, queue_size=1)
    rate = rospy.Rate(RATE)

    # TODO waypoint send efficiently

    # polygon message for 3 robots
    wp_msg = waypoint_generator(1,5, 4,0, -4,0)

    # start publish
    try:
        while not rospy.is_shutdown():
            waypoint_publisher.publish(wp_msg)
            rate.sleep()

    except rospy.ROSInterruptException:
        rospy.logerr("ROS node interrupted.")

if __name__ == "__main__":
    """Run the main function."""
    main()
